cas:
  server:
    host:
      url: http://10.10.1.79:8081/cas  #CAS服务地址
      login_url: ${cas.server.host.url}/login   #CAS服务登录地址
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}    #CAS服务登出地址
app:
  server:
    host:
      url: http://10.10.1.79:7070  #应用访问地址
  login:
    url: /login   #应用登录地址
  logout:
    url: /logout  #应用登出地址
server:
  port: 7070
